# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trace2mermaid < Formula
  desc "CLI for converting OpenTelemetry traces to Mermaid Gantt diagrams"
  homepage "https://github.com/mheap/trace2mermaid"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mheap/trace2mermaid/releases/download/v0.1.0/trace2mermaid_0.1.0_darwin_amd64.tar.gz"
      sha256 "9c440c7ad698fa84f4b1ee23860cf17d5ba8d9a9f19c3f3a4fd416555b17ce20"

      define_method(:install) do
        bin.install "trace2mermaid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mheap/trace2mermaid/releases/download/v0.1.0/trace2mermaid_0.1.0_darwin_arm64.tar.gz"
      sha256 "78dd9b44f219d983fffafbd0f05d766af0998aa55db53a3bc41baca393b31646"

      define_method(:install) do
        bin.install "trace2mermaid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/trace2mermaid/releases/download/v0.1.0/trace2mermaid_0.1.0_linux_amd64.tar.gz"
      sha256 "6094aab82dbd83b39e429ea8a42bd8043b5896cbb0e37fe6d7c451022e54244c"
      define_method(:install) do
        bin.install "trace2mermaid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/trace2mermaid/releases/download/v0.1.0/trace2mermaid_0.1.0_linux_arm64.tar.gz"
      sha256 "abafafa8460decb34b46fb401319f3dfb2d843198154169c9e19a06b4882acdf"
      define_method(:install) do
        bin.install "trace2mermaid"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/trace2mermaid --version")
  end
end
