# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentEnPlace < Formula
  desc "Build on-demand Docker containers for projects + agentic coding using mise"
  homepage "https://github.com/mheap/agent-en-place"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.3.0/agent-en-place_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "d1f3ec8a2b4dad285d9f4e13c2d599f41ab888199e09702de852b5ee244cae72"

      def install
        bin.install "agent-en-place"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.3.0/agent-en-place_0.3.0_Darwin_arm64.tar.gz"
      sha256 "6e8cb3cbae6a2f111cb59a4a144d7d0f0c8c9e2c17044db5545a188788993c34"

      def install
        bin.install "agent-en-place"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.3.0/agent-en-place_0.3.0_Linux_x86_64.tar.gz"
      sha256 "a1b60bf4ca44c174f2c1564563403d823f84908a4a0d28aa6ba9beb7aa5223c2"
      def install
        bin.install "agent-en-place"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.3.0/agent-en-place_0.3.0_Linux_arm64.tar.gz"
      sha256 "3d8e515493cfb273874e4de241d83ab111c6cdef8fd93949c96394ce9de6be60"
      def install
        bin.install "agent-en-place"
      end
    end
  end

  def caveats
    <<~EOS
      To use agent-en-place, add this function to your shell config (.bashrc, .zshrc, etc.):

        function vibe() { bash -lc "$(agent-en-place $1)" }

      Then run: vibe <provider>
      Supported providers: codex, opencode, copilot
    EOS
  end

  test do
    system "#{bin}/agent-en-place", "--version"
  end
end
