# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentEnPlace < Formula
  desc "Build on-demand Docker containers for projects + agentic coding using mise"
  homepage "https://github.com/mheap/agent-en-place"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.2.0/agent-en-place_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "14144a12fc8c826bdbded5ac7efddb5df6a73e37c7f1c7a3c217963d1286620e"

      def install
        bin.install "agent-en-place"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.2.0/agent-en-place_0.2.0_Darwin_arm64.tar.gz"
      sha256 "29b7895798d5f870fb27063906107bca659219480b60ec81d0b47e3a9ea2127e"

      def install
        bin.install "agent-en-place"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.2.0/agent-en-place_0.2.0_Linux_x86_64.tar.gz"
      sha256 "3d68ef01b2408770a8504402358691d78ccc13b137e974444fc3e7b5cd9a6ce5"
      def install
        bin.install "agent-en-place"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.2.0/agent-en-place_0.2.0_Linux_arm64.tar.gz"
      sha256 "add0c5621f61fbc873d525790ba1632debbcf71bb5551ac29f91259ddf15ed02"
      def install
        bin.install "agent-en-place"
      end
    end
  end

  def caveats
    <<~EOS
      To use agent-en-place, add this function to your shell config (.bashrc, .zshrc, etc.):

        function vibe() { bash -lc "$(agent-en-place $1)" }

      Then run: vibe <provider>
      Supported providers: codex, opencode, copilot
    EOS
  end

  test do
    system "#{bin}/agent-en-place", "--version"
  end
end
