# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentEnPlace < Formula
  desc "Build on-demand Docker containers for projects + agentic coding using mise"
  homepage "https://github.com/mheap/agent-en-place"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.4.0/agent-en-place_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "85f22429e694be3ee54286fe1a38611f32c3717940bb7ba506f16b4854a63672"

      define_method(:install) do
        bin.install "agent-en-place"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.4.0/agent-en-place_0.4.0_Darwin_arm64.tar.gz"
      sha256 "0d4521ae6f765ad55370b195b05fd69dcb261b61c72e63810e3f297c36b038b5"

      define_method(:install) do
        bin.install "agent-en-place"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.4.0/agent-en-place_0.4.0_Linux_x86_64.tar.gz"
      sha256 "fa483e3b20e8038887596fd8565fe4b827ae6d156f96d32d04f48e2b34b66055"
      define_method(:install) do
        bin.install "agent-en-place"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/agent-en-place/releases/download/v0.4.0/agent-en-place_0.4.0_Linux_arm64.tar.gz"
      sha256 "b2cc4e6921c1c8598ef9087541325cf1a3df7456d28e63ae1a5ab17be0b32f9c"
      define_method(:install) do
        bin.install "agent-en-place"
      end
    end
  end

  def caveats
    <<~EOS
      To use agent-en-place, add this function to your shell config (.bashrc, .zshrc, etc.):

        function vibe() { bash -lc "$(agent-en-place $1)" }

      Then run: vibe <provider>
      Supported providers: codex, opencode, copilot
    EOS
  end

  test do
    system "#{bin}/agent-en-place", "--version"
  end
end
