# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleContactsBackup < Formula
  desc "Backup and restore Google Contacts to/from a JSON file"
  homepage "https://github.com/mheap/google-contacts-backup"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mheap/google-contacts-backup/releases/download/v0.2.0/google-contacts-backup_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "e11cf575add6e4b3edca31bc458fd7472b854634665ef0aff9fff49843b23ce1"

      def install
        bin.install "google-contacts-backup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mheap/google-contacts-backup/releases/download/v0.2.0/google-contacts-backup_0.2.0_Darwin_arm64.tar.gz"
      sha256 "0fe617ad9efcd59241c6a91316424d8788f9181a598295a09dbfcc5ddb244d77"

      def install
        bin.install "google-contacts-backup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/google-contacts-backup/releases/download/v0.2.0/google-contacts-backup_0.2.0_Linux_x86_64.tar.gz"
      sha256 "733c19ee20db84f957a83aabd4d8d75bce6df11d785de7e7556947b7bf823b34"
      def install
        bin.install "google-contacts-backup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/google-contacts-backup/releases/download/v0.2.0/google-contacts-backup_0.2.0_Linux_arm64.tar.gz"
      sha256 "6bc16d1287e42356c5ac14640997c10a24255b573925ee304ea47856bf5caa24"
      def install
        bin.install "google-contacts-backup"
      end
    end
  end

  test do
    system "#{bin}/google-contacts-backup", "--version"
  end
end
