# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleContactsBackup < Formula
  desc "Backup and restore Google Contacts to/from a JSON file"
  homepage "https://github.com/mheap/google-contacts-backup"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mheap/google-contacts-backup/releases/download/v0.1.0/google-contacts-backup_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "0ac61931e684236db1c4a1991ee82b3ad6b1b42ad7dde9588096d410b0c31a9f"

      def install
        bin.install "google-contacts-backup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mheap/google-contacts-backup/releases/download/v0.1.0/google-contacts-backup_0.1.0_Darwin_arm64.tar.gz"
      sha256 "41a067a880bc4ff6c827e579aff5ffe35d4785155e188a108ec09c6a5ca1a308"

      def install
        bin.install "google-contacts-backup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/google-contacts-backup/releases/download/v0.1.0/google-contacts-backup_0.1.0_Linux_x86_64.tar.gz"
      sha256 "f22b2c5ee11ed75c36f049361d91b0b937dd6739d2a92c948ca802d5e986b7fa"
      def install
        bin.install "google-contacts-backup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mheap/google-contacts-backup/releases/download/v0.1.0/google-contacts-backup_0.1.0_Linux_arm64.tar.gz"
      sha256 "98935336377cf7271ed7e63b08247659e28117cc1121745dbaf42c7722ae23cc"
      def install
        bin.install "google-contacts-backup"
      end
    end
  end

  test do
    system "#{bin}/google-contacts-backup", "--version"
  end
end
