# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Listentotaxman < Formula
  desc "CLI for calculating UK tax and national insurance"
  homepage "https://github.com/mheap/listentotaxman-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mheap/listentotaxman-cli/releases/download/v0.1.0/listentotaxman_0.1.0_darwin_amd64.tar.gz"
      sha256 "1a0cf33c09e75c44f3b120bec8fedde90cd1ccbf324b455f30b82f7294091e7d"

      def install
        bin.install "listentotaxman"
        bash_completion.install "completions/listentotaxman.bash" => "listentotaxman"
        zsh_completion.install "completions/listentotaxman.zsh" => "_listentotaxman"
        fish_completion.install "completions/listentotaxman.fish"
      end
    end
    on_arm do
      url "https://github.com/mheap/listentotaxman-cli/releases/download/v0.1.0/listentotaxman_0.1.0_darwin_arm64.tar.gz"
      sha256 "820f3754796b0b1548ebcfd5404537996d22e484b4f2a90d764cfbf780c4b154"

      def install
        bin.install "listentotaxman"
        bash_completion.install "completions/listentotaxman.bash" => "listentotaxman"
        zsh_completion.install "completions/listentotaxman.zsh" => "_listentotaxman"
        fish_completion.install "completions/listentotaxman.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mheap/listentotaxman-cli/releases/download/v0.1.0/listentotaxman_0.1.0_linux_amd64.tar.gz"
        sha256 "299eb7f5a86318b61c9a5f686a999ceb720138bcdaf00b7b12db98024e68fb26"

        def install
          bin.install "listentotaxman"
          bash_completion.install "completions/listentotaxman.bash" => "listentotaxman"
          zsh_completion.install "completions/listentotaxman.zsh" => "_listentotaxman"
          fish_completion.install "completions/listentotaxman.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mheap/listentotaxman-cli/releases/download/v0.1.0/listentotaxman_0.1.0_linux_arm64.tar.gz"
        sha256 "91ff55f46be9e096249c5eca3c9a9fd7d0b5f054bc5d82fcfb4b9235c645d3c0"

        def install
          bin.install "listentotaxman"
          bash_completion.install "completions/listentotaxman.bash" => "listentotaxman"
          zsh_completion.install "completions/listentotaxman.zsh" => "_listentotaxman"
          fish_completion.install "completions/listentotaxman.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/listentotaxman", "version"
  end
end
